#!/bin/bash
set -e

echo "Creating $UMAMI_DB_USER user and $UMAMI_DB_NAME database..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $UMAMI_DB_USER WITH PASSWORD '$UMAMI_DB_PASSWORD';
    CREATE DATABASE $UMAMI_DB_NAME OWNER $UMAMI_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $UMAMI_DB_NAME TO $UMAMI_DB_USER;
EOSQL

echo "Creating $SHORTENER_DB_USER user and $SHORTENER_DB_NAME database..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SHORTENER_DB_USER WITH PASSWORD '$SHORTENER_DB_PASSWORD';
    CREATE DATABASE $SHORTENER_DB_NAME OWNER $SHORTENER_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $SHORTENER_DB_NAME TO $SHORTENER_DB_USER;
EOSQL

echo "Creating $SAQ_SOMMELIER_DB_USER user and $SAQ_SOMMELIER_DB_NAME database..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SAQ_SOMMELIER_DB_USER WITH PASSWORD '$SAQ_SOMMELIER_DB_PASSWORD';
    CREATE DATABASE $SAQ_SOMMELIER_DB_NAME OWNER $SAQ_SOMMELIER_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $SAQ_SOMMELIER_DB_NAME TO $SAQ_SOMMELIER_DB_USER;
EOSQL

echo "Database initialization completed successfully!"
